site_name: pinax-eventlog
pages:
- [index.md, Home]
- [usage.md, Usage]
- [signals.md, Signals]
- [changelog.md, Change Log]
theme: readthedocs
repo_url: https://github.com/pinax/pinax-eventlog
site_description: "an event logger for Django projects"
site_author: "Pinax Team"
markdown_extensions: [admonition]
